//USERS
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_RESET = "USER_LOGIN_RESET";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";
export const USER_SIGNUP_RESET = "USER_SIGNUP_RESET";

export const UPDATE_ME_REQUEST = "UPDATE_ME_REQUEST";
export const UPDATE_ME_SUCCESS = "UPDATE_ME_SUCCESS";
export const UPDATE_ME_FAIL = "UPDATE_ME_FAIL";
export const UPDATE_ME_RESET = "UPDATE_ME_RESET";

//BOARDS
export const FETCH_MY_BOARDS_REQUEST = "FETCH_MY_BOARDS_REQUEST";
export const FETCH_MY_BOARDS_SUCCESS = "FETCH_MY_BOARDS_SUCCESS";
export const FETCH_MY_BOARDS_FAIL = "FETCH_MY_BOARDS_FAIL";

export const FETCH_FULL_BOARD_REQUEST = "FETCH_FULL_BOARD_REQUEST";
export const FETCH_FULL_BOARD_SUCCESS = "FETCH_FULL_BOARD_SUCCESS";
export const FETCH_FULL_BOARD_FAIL = "FETCH_FULL_BOARD_FAIL";
export const FETCH_FULL_BOARD_RESET = "FETCH_FULL_BOARD_RESET";

export const UPDATE_BOARD_REQUEST = "UPDATE_BOARD_REQUEST";
export const UPDATE_BOARD_SUCCESS = "UPDATE_BOARD_SUCCESS";
export const UPDATE_BOARD_FAIL = "UPDATE_BOARD_FAIL";

export const DELETE_BOARD_REQUEST = "DELETE_BOARD_REQUEST";
export const DELETE_BOARD_SUCCESS = "DELETE_BOARD_SUCCESS";
export const DELETE_BOARD_FAIL = "DELETE_BOARD_FAIL";
export const DELETE_BOARD_RESET = "DELETE_BOARD_RESET";

//SETS
export const CREATE_SET_REQUEST = "CREATE_SET_REQUEST";
export const CREATE_SET_SUCCESS = "CREATE_SET_SUCCESS";
export const CREATE_SET_FAIL = "CREATE_SET_FAIL";

export const SWAP_SET_REQUEST = "SWAP_SET_REQUEST";
export const SWAP_SET_SUCCESS = "SWAP_SET_SUCCESS";
export const SWAP_SET_FAIL = "SWAP_SET_FAIL";

export const UPDATE_SET_REQUEST = "UPDATE_SET_REQUEST";
export const UPDATE_SET_SUCCESS = "UPDATE_SET_SUCCESS";
export const UPDATE_SET_FAIL = "UPDATE_SET_FAIL";

export const DELETE_SET_REQUEST = "DELETE_SET_REQUEST";
export const DELETE_SET_SUCCESS = "DELETE_SET_SUCCESS";
export const DELETE_SET_FAIL = "DELETE_SET_FAIL";

//TASKS
export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAIL = "CREATE_TASK_FAIL";

export const SWAP_TASK_REQUEST = "SWAP_TASK_REQUEST";
export const SWAP_TASK_SUCCESS = "SWAP_TASK_SUCCESS";
export const SWAP_TASK_FAIL = "SWAP_TASK_FAIL";

export const SWITCH_TASK_REQUEST = "SWITCH_TASK_REQUEST";
export const SWITCH_TASK_SUCCESS = "SWITCH_TASK_SUCCESS";
export const SWITCH_TASK_FAIL = "SWITCH_TASK_FAIL";

export const UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAIL = "UPDATE_TASK_FAIL";

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";

export const IS_COMPLETED_TASK_REQUEST = "IS_COMPLETED_TASK_REQUEST";
export const IS_COMPLETED_TASK_SUCCESS = "IS_COMPLETED_TASK_SUCCESS";
export const IS_COMPLETED_TASK_FAIL = "IS_COMPLETED_TASK_FAIL";

//UPLOAD
export const UPLOAD_PROFILE_PICTURE_REQUEST = "UPLOAD_PROFILE_PICTURE_REQUEST";
export const UPLOAD_PROFILE_PICTURE_SUCCESS = "UPLOAD_PROFILE_PICTURE_SUCCESS";
export const UPLOAD_PROFILE_PICTURE_FAIL = "UPLOAD_PROFILE_PICTURE_FAIL";
