//USERS
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_RESET = "USER_LOGIN_RESET";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";
export const USER_SIGNUP_RESET = "USER_SIGNUP_RESET";

//BOARDS
export const FETCH_MY_BOARDS_REQUEST = "FETCH_MY_BOARDS_REQUEST";
export const FETCH_MY_BOARDS_SUCCESS = "FETCH_MY_BOARDS_SUCCESS";
export const FETCH_MY_BOARDS_FAIL = "FETCH_MY_BOARDS_FAIL";

export const FETCH_FULL_BOARD_REQUEST = "FETCH_FULL_BOARD_REQUEST";
export const FETCH_FULL_BOARD_SUCCESS = "FETCH_FULL_BOARD_SUCCESS";
export const FETCH_FULL_BOARD_FAIL = "FETCH_FULL_BOARD_FAIL";
export const FETCH_FULL_BOARD_RESET = "FETCH_FULL_BOARD_RESET";

//SETS
export const CREATE_SET_REQUEST = "CREATE_SET_REQUEST";
export const CREATE_SET_SUCCESS = "CREATE_SET_SUCCESS";
export const CREATE_SET_FAIL = "CREATE_SET_FAIL";

export const SWAP_SET_REQUEST = "SWAP_SET_REQUEST";
export const SWAP_SET_SUCCESS = "SWAP_SET_SUCCESS";
export const SWAP_SET_FAIL = "SWAP_SET_FAIL";

//TASKS
export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAIL = "CREATE_TASK_FAIL";

export const SWAP_TASK_REQUEST = "SWAP_TASK_REQUEST";
export const SWAP_TASK_SUCCESS = "SWAP_TASK_SUCCESS";
export const SWAP_TASK_FAIL = "SWAP_TASK_FAIL";
